[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.0.0-rc.5", features = [
    "sqlx-postgres",
    "tokio",
    "macros",
] }
actix-web = "4.9.0"
dotenv = "0.15.0"
